adjective1 = input("insert an adjective.\n")
noun1 = input("insert a noun.\n")
pluralNoun = input("insert a plural noun.\n")
person = input("insert a female person.\n")
adjective2 = input("insert another adjective.\n")
clothing = input("insert a article of clothing.\n")
Noun2 = input("insert another noun./\n")
City = input("insert a city\n")
pluralNoun2 = input("insert another plural noun\n")
adjective3 = input("insert another adjective\n")
body = input
letter = input
celebrity = input
PluralNoun3 = input
adjective4 = input
place = input
body2 = input
adjective5 = input
adjective6 = input
verb =  input
pluralNoun4 = input
number = input
print("There are many"  adjective1  "ways to choose a"  noun1  "to read. First, you could ask for recommendations from your friends and"  pluralNoun  ". Just don't ask Aunt"  person  " she only reads ")